# Generated by Django 5.0.9 on 2024-10-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=8)),
                ('CreatedAt', models.DateField()),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
