# Generated by Django 5.0.9 on <fecha>

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_producto'),  # Cambia esto para que apunte a la migración correcta
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='moneda',
            field=models.CharField(
                max_length=3,
                choices=[
                    ('MXN', 'Pesos Mexicanos'),
                    ('USD', 'Dólares Americanos')
                ],
                default='MXN'
            ),
        ),
    ]
