# Generated by Django 5.0.9 on 2024-10-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_producto_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('PZA', 'Piezas'), ('METROS', 'Metros'), ('LITROS', 'Litros'), ('CAJAS', 'Cajas')], default='PZA', max_length=6),
        ),
    ]
