# Generated by Django 5.0.9 on 2024-10-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_producto_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
