# Generated by Django 5.0.9 on 2024-10-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_producto_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('proveedor', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateField()),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('moneda', models.CharField(choices=[('MXN', 'Pesos'), ('USD', 'Dólares')], max_length=3)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEliminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('proveedor', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateField()),
                ('numero_serie', models.CharField(max_length=255)),
                ('moneda', models.CharField(max_length=10)),
                ('unidad', models.CharField(max_length=10)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
