# Generated by Django 5.0.9 on 2024-11-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_nuevoproduct_productoeliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('existente', 'Existente')], default='nuevo', max_length=10),
        ),
    ]
