# Generated by Django 5.0.9 on 2024-11-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_primerasentradas_delete_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_maxima',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_minima',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre_proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad',
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_categoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
