# Generated by Django 5.0.9 on 2024-11-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_producto_id_alter_producto_nombre_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_producto',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_categoria',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
