# Generated by Django 5.0.9 on 2024-11-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_remove_producto_categoria_remove_producto_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerasentradas',
            name='maneja_cantidad_min_max',
        ),
        migrations.RemoveField(
            model_name='primerasentradas',
            name='nombre_categoria',
        ),
        migrations.RemoveField(
            model_name='primerasentradas',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='primerasentradas',
            name='nombre_proveedor',
        ),
        migrations.AddField(
            model_name='primerasentradas',
            name='proveedor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='primerasentradas',
            name='cantidad_maxima',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='primerasentradas',
            name='cantidad_minima',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='primerasentradas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='primerasentradas',
            name='moneda',
            field=models.CharField(default='MXN', max_length=10),
        ),
        migrations.AlterField(
            model_name='primerasentradas',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=100),
        ),
    ]
