# Generated by Django 5.0.9 on 2024-11-26 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_remove_primerasentradas_maneja_cantidad_min_max_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='nombre_categoria',
        ),
    ]
