# Generated by Django 5.0.9 on 2024-11-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_rename_nombre_categoria_nombre_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='contacto_correo',
            field=models.EmailField(default='correo@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='credito_termino',
            field=models.CharField(default='Sin término de crédito', max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=255),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='giro_sector',
            field=models.CharField(default='No especificado', max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='moneda',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(default='Sin especificar', max_length=15),
        ),
    ]
