# Generated by Django 5.0.9 on 2024-12-02 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_proveedor_contacto_correo_proveedor_credito_termino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerasentradas',
            name='nombre_proveedor',
            field=models.CharField(default='Proveedor Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='primerasentradas',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.proveedor'),
        ),
    ]
