# Generated by Django 5.0.9 on 2024-12-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_primerasentradas_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerasentradas',
            name='cantidad_maxima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primerasentradas',
            name='cantidad_minima',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
