# Generated by Django 5.0.9 on 2024-12-02 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_alter_primerasentradas_cantidad_maxima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerasentradas',
            name='unidad',
        ),
        migrations.AlterField(
            model_name='primerasentradas',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='primerasentradas',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.categoria'),
        ),
        migrations.AlterField(
            model_name='primerasentradas',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primerasentradas',
            name='moneda',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='primerasentradas',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='primerasentradas',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.producto'),
        ),
        migrations.AlterField(
            model_name='primerasentradas',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.proveedor'),
        ),
    ]
