# Generated by Django 5.0.9 on 2024-12-09 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_remove_primerasentradas_unidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEntradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
                ('campo2', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='primerasentradas',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.categoria'),
        ),
        migrations.AlterField(
            model_name='primerasentradas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
